dataset: 'year'
task: 'regression'
resume_dir: './checkpoint/checkpoint.pth'
logname: 'year.log'

fit:
  max_epochs: 150
  patience: 80
  lr: 0.008

model:
  layer: 20
  base_outdim: 64
  k: 5
  drop_rate: 0.1